"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  createDeviceLinkAction,
  type DeviceLinkCode,
} from "@/app/actions/device-link";
import { Button } from "@/components/ui/button";

type Panel = {
  code: DeviceLinkCode;
  secondsLeft: number;
};

/**
 * Signs in another device by scanning a code.
 *
 * The code is short-lived, single use, and generated by a session that is
 * already signed in. That is the whole security model: the phone in your
 * hand vouches for the new one.
 *
 * It regenerates before expiry so the screen never shows a dead code, and it
 * is never printed — a printed sign-in code is a credential anyone can
 * photograph off the wall.
 */
export function DeviceLink() {
  const [panel, setPanel] = useState<Panel | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const generating = useRef(false);

  const generate = useCallback(async () => {
    if (generating.current) return;
    generating.current = true;
    setBusy(true);
    try {
      const code = await createDeviceLinkAction();
      setPanel({ code, secondsLeft: code.expiresInSeconds });
      setError(null);
    } catch {
      setError("Could not create a code. Try again.");
    } finally {
      generating.current = false;
      setBusy(false);
    }
  }, []);

  // The countdown only ever updates from inside the interval callback, and
  // regeneration is triggered from there too rather than from an effect.
  useEffect(() => {
    if (!panel) return;
    const id = setInterval(() => {
      setPanel((current) => {
        if (!current) return current;
        if (current.secondsLeft <= 1) {
          void generate();
          return { ...current, secondsLeft: 0 };
        }
        return { ...current, secondsLeft: current.secondsLeft - 1 };
      });
    }, 1000);
    return () => clearInterval(id);
  }, [panel, generate]);

  if (!panel && !busy) {
    return (
      <div>
        <Button variant="outline" onClick={generate}>
          Sign in another device
        </Button>
        {error && <p className="mt-2 text-sm text-accent">{error}</p>}
      </div>
    );
  }

  return (
    <div className="rounded-[3px] border border-line bg-surface p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h3 className="font-display text-lg font-bold">Scan to sign in</h3>
          <p className="mt-1 max-w-sm text-sm text-bone-2">
            Point the other phone&rsquo;s camera at this. It signs that device
            in as you.
          </p>
        </div>
        <button
          type="button"
          onClick={() => setPanel(null)}
          className="text-sm text-bone-3 hover:text-bone"
        >
          Close
        </button>
      </div>

      <div className="mt-5 flex flex-wrap items-center gap-6">
        <div className="rounded-[3px] bg-white p-3">
          {panel ? (
            <div
              className="device-qr"
              aria-label="Sign-in code"
              dangerouslySetInnerHTML={{ __html: panel.code.svg }}
            />
          ) : (
            <div className="h-[180px] w-[180px] animate-pulse bg-neutral-200" />
          )}
        </div>

        <div className="text-sm">
          <p className="tabular-nums text-bone-2">
            Expires in {panel?.secondsLeft ?? 0}s
          </p>
          <p className="mt-1 text-bone-3">Refreshes automatically.</p>
          {error && <p className="mt-2 text-accent">{error}</p>}
        </div>
      </div>

      <p className="mt-5 border-t border-line pt-4 text-xs text-bone-3">
        This is not the shop&rsquo;s booking code. Anyone who scans this is
        signed in as you &mdash; don&rsquo;t print it, and don&rsquo;t leave it
        on screen.
      </p>
    </div>
  );
}
